language: node_js
node_js:
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.2"
  - "5.5"
sudo: false
before_install:
  - pip install codecov
script:
  - "npm run-script test-travis"
after_success:
  - codecov
